version: '3.9'

services:
  api:
    build: .
    container_name: synapse-server
    ports:
      - '8787:8787'
    environment:
      - NODE_ENV=production
      - PORT=8787
      - JWT_SECRET=${JWT_SECRET}
      - CORS_ORIGIN=${CORS_ORIGIN:-http://localhost:5173}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT:-587}
      - SMTP_SECURE=${SMTP_SECURE:-false}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - EMAIL_FROM=${EMAIL_FROM}
      - EMAIL_TO=${EMAIL_TO}
      - REMOTION_COMPOSITION_ID=${REMOTION_COMPOSITION_ID:-MainComposition}
    volumes:
      - output:/app/server/output
    restart: unless-stopped

volumes:
  output:
