// Built-in theme definitions for the code editor

import type { ThemeDefinition } from './types';

export const BUILT_IN_THEMES: ThemeDefinition[] = [
  // VS Code Dark+ (Default Dark)
  {
    id: 'vscode-dark-plus',
    name: 'VS Code Dark+',
    category: 'dark',
    colors: {
      background: '#1e1e1e',
      foreground: '#d4d4d4',
      comment: '#6a9955',
      keyword: '#c586c0',
      string: '#ce9178',
      number: '#b5cea8',
      operator: '#d4d4d4',
      punctuation: '#d4d4d4',
      function: '#dcdcaa',
      variable: '#9cdcfe',
      type: '#4ec9b0',
      class: '#4ec9b0',
      constant: '#4fc1ff',
      property: '#9cdcfe',
      tag: '#569cd6',
      attribute: '#92c5f8',
      boolean: '#569cd6',
      regex: '#d16969',
      escape: '#d7ba7d',
      selection: '#264f78',
      lineHighlight: '#2a2d2e',
      cursor: '#d4d4d4',
      diffAdded: '#144212',
      diffRemoved: '#5a1e1e',
      diffModified: '#1e3a8a',
    },
    fonts: {
      monospace: 'Consolas, "Courier New", monospace',
      size: 14,
      lineHeight: 1.5,
    },
    metadata: {
      author: 'Microsoft',
      description: 'The default dark theme from Visual Studio Code',
      version: '1.0.0',
      tags: ['popular', 'default', 'professional'],
    },
  },

  // VS Code Light+ (Default Light)
  {
    id: 'vscode-light-plus',
    name: 'VS Code Light+',
    category: 'light',
    colors: {
      background: '#ffffff',
      foreground: '#24292e',
      comment: '#6a737d',
      keyword: '#d73a49',
      string: '#032f62',
      number: '#005cc5',
      operator: '#24292e',
      punctuation: '#24292e',
      function: '#6f42c1',
      variable: '#e36209',
      type: '#005cc5',
      class: '#6f42c1',
      constant: '#005cc5',
      property: '#e36209',
      tag: '#22863a',
      attribute: '#6f42c1',
      boolean: '#005cc5',
      regex: '#032f62',
      escape: '#032f62',
      selection: '#c8e1ff',
      lineHighlight: '#f6f8fa',
      cursor: '#24292e',
      diffAdded: '#e6ffed',
      diffRemoved: '#ffeef0',
      diffModified: '#e1f5fe',
    },
    fonts: {
      monospace: 'Consolas, "Courier New", monospace',
      size: 14,
      lineHeight: 1.5,
    },
    metadata: {
      author: 'Microsoft',
      description: 'The default light theme from Visual Studio Code',
      version: '1.0.0',
      tags: ['popular', 'default', 'professional'],
    },
  },

  // GitHub Dark
  {
    id: 'github-dark',
    name: 'GitHub Dark',
    category: 'dark',
    colors: {
      background: '#0d1117',
      foreground: '#c9d1d9',
      comment: '#8b949e',
      keyword: '#ff7b72',
      string: '#a5d6ff',
      number: '#79c0ff',
      operator: '#ff7b72',
      punctuation: '#c9d1d9',
      function: '#d2a8ff',
      variable: '#ffa657',
      type: '#ffa198',
      class: '#ffa198',
      constant: '#79c0ff',
      property: '#79c0ff',
      tag: '#7ee787',
      attribute: '#79c0ff',
      boolean: '#79c0ff',
      regex: '#a5d6ff',
      escape: '#a5d6ff',
      selection: '#264f78',
      lineHighlight: '#161b22',
      cursor: '#c9d1d9',
      diffAdded: '#238636',
      diffRemoved: '#da3633',
      diffModified: '#1f6feb',
    },
    fonts: {
      monospace: 'SFMono-Regular, Consolas, "Liberation Mono", Menlo, monospace',
      size: 14,
      lineHeight: 1.45,
    },
    metadata: {
      author: 'GitHub',
      description: 'GitHub\'s dark theme for code',
      version: '1.0.0',
      tags: ['popular', 'github', 'modern'],
    },
  },

  // GitHub Light
  {
    id: 'github-light',
    name: 'GitHub Light',
    category: 'light',
    colors: {
      background: '#ffffff',
      foreground: '#24292f',
      comment: '#6e7781',
      keyword: '#cf222e',
      string: '#0a3069',
      number: '#0550ae',
      operator: '#cf222e',
      punctuation: '#24292f',
      function: '#8250df',
      variable: '#953800',
      type: '#cf222e',
      class: '#cf222e',
      constant: '#0550ae',
      property: '#0550ae',
      tag: '#116329',
      attribute: '#0550ae',
      boolean: '#0550ae',
      regex: '#0a3069',
      escape: '#0a3069',
      selection: '#0969da',
      lineHighlight: '#f6f8fa',
      cursor: '#24292f',
      diffAdded: '#dafbe1',
      diffRemoved: '#ffebe9',
      diffModified: '#ddf4ff',
    },
    fonts: {
      monospace: 'SFMono-Regular, Consolas, "Liberation Mono", Menlo, monospace',
      size: 14,
      lineHeight: 1.45,
    },
    metadata: {
      author: 'GitHub',
      description: 'GitHub\'s light theme for code',
      version: '1.0.0',
      tags: ['popular', 'github', 'modern'],
    },
  },

  // Dracula
  {
    id: 'dracula',
    name: 'Dracula',
    category: 'dark',
    colors: {
      background: '#282a36',
      foreground: '#f8f8f2',
      comment: '#6272a4',
      keyword: '#ff79c6',
      string: '#f1fa8c',
      number: '#bd93f9',
      operator: '#ff79c6',
      punctuation: '#f8f8f2',
      function: '#50fa7b',
      variable: '#8be9fd',
      type: '#8be9fd',
      class: '#50fa7b',
      constant: '#bd93f9',
      property: '#50fa7b',
      tag: '#ff79c6',
      attribute: '#50fa7b',
      boolean: '#bd93f9',
      regex: '#f1fa8c',
      escape: '#f1fa8c',
      selection: '#44475a',
      lineHighlight: '#44475a',
      cursor: '#f8f8f2',
      diffAdded: '#50fa7b',
      diffRemoved: '#ff5555',
      diffModified: '#ffb86c',
    },
    fonts: {
      monospace: 'Monaco, Menlo, "Ubuntu Mono", monospace',
      size: 14,
      lineHeight: 1.5,
    },
    metadata: {
      author: 'Dracula Theme',
      description: 'A dark theme for many editors, shells, and more',
      version: '1.0.0',
      tags: ['popular', 'colorful', 'vampire'],
    },
  },

  // Monokai
  {
    id: 'monokai',
    name: 'Monokai',
    category: 'dark',
    colors: {
      background: '#272822',
      foreground: '#f8f8f2',
      comment: '#75715e',
      keyword: '#f92672',
      string: '#e6db74',
      number: '#ae81ff',
      operator: '#f8f8f2',
      punctuation: '#f8f8f2',
      function: '#a6e22e',
      variable: '#fd971f',
      type: '#66d9ef',
      class: '#a6e22e',
      constant: '#ae81ff',
      property: '#a6e22e',
      tag: '#f92672',
      attribute: '#a6e22e',
      boolean: '#ae81ff',
      regex: '#e6db74',
      escape: '#ae81ff',
      selection: '#49483e',
      lineHighlight: '#3e3d32',
      cursor: '#f8f8f0',
      diffAdded: '#a6e22e',
      diffRemoved: '#f92672',
      diffModified: '#fd971f',
    },
    fonts: {
      monospace: 'Monaco, Menlo, "Ubuntu Mono", monospace',
      size: 14,
      lineHeight: 1.5,
    },
    metadata: {
      author: 'Wimer Hazenberg',
      description: 'The original Monokai color scheme',
      version: '1.0.0',
      tags: ['classic', 'popular', 'sublime'],
    },
  },

  // Solarized Dark
  {
    id: 'solarized-dark',
    name: 'Solarized Dark',
    category: 'dark',
    colors: {
      background: '#002b36',
      foreground: '#93a1a1',
      comment: '#586e75',
      keyword: '#859900',
      string: '#2aa198',
      number: '#b58900',
      operator: '#93a1a1',
      punctuation: '#93a1a1',
      function: '#268bd2',
      variable: '#cb4b16',
      type: '#b58900',
      class: '#268bd2',
      constant: '#b58900',
      property: '#268bd2',
      tag: '#859900',
      attribute: '#b58900',
      boolean: '#b58900',
      regex: '#2aa198',
      escape: '#dc322f',
      selection: '#073642',
      lineHighlight: '#073642',
      cursor: '#93a1a1',
      diffAdded: '#859900',
      diffRemoved: '#dc322f',
      diffModified: '#b58900',
    },
    fonts: {
      monospace: 'Monaco, Menlo, "Ubuntu Mono", monospace',
      size: 14,
      lineHeight: 1.5,
    },
    metadata: {
      author: 'Ethan Schoonover',
      description: 'Precision colors for machines and people',
      version: '1.0.0',
      tags: ['classic', 'scientific', 'balanced'],
    },
  },

  // Solarized Light
  {
    id: 'solarized-light',
    name: 'Solarized Light',
    category: 'light',
    colors: {
      background: '#fdf6e3',
      foreground: '#657b83',
      comment: '#93a1a1',
      keyword: '#859900',
      string: '#2aa198',
      number: '#b58900',
      operator: '#657b83',
      punctuation: '#657b83',
      function: '#268bd2',
      variable: '#cb4b16',
      type: '#b58900',
      class: '#268bd2',
      constant: '#b58900',
      property: '#268bd2',
      tag: '#859900',
      attribute: '#b58900',
      boolean: '#b58900',
      regex: '#2aa198',
      escape: '#dc322f',
      selection: '#eee8d5',
      lineHighlight: '#eee8d5',
      cursor: '#657b83',
      diffAdded: '#859900',
      diffRemoved: '#dc322f',
      diffModified: '#b58900',
    },
    fonts: {
      monospace: 'Monaco, Menlo, "Ubuntu Mono", monospace',
      size: 14,
      lineHeight: 1.5,
    },
    metadata: {
      author: 'Ethan Schoonover',
      description: 'Precision colors for machines and people',
      version: '1.0.0',
      tags: ['classic', 'scientific', 'balanced'],
    },
  },

  // One Dark Pro
  {
    id: 'one-dark-pro',
    name: 'One Dark Pro',
    category: 'dark',
    colors: {
      background: '#282c34',
      foreground: '#abb2bf',
      comment: '#5c6370',
      keyword: '#c678dd',
      string: '#98c379',
      number: '#d19a66',
      operator: '#56b6c2',
      punctuation: '#abb2bf',
      function: '#61afef',
      variable: '#e06c75',
      type: '#e5c07b',
      class: '#e5c07b',
      constant: '#d19a66',
      property: '#e06c75',
      tag: '#e06c75',
      attribute: '#d19a66',
      boolean: '#d19a66',
      regex: '#98c379',
      escape: '#56b6c2',
      selection: '#3e4451',
      lineHighlight: '#2c313c',
      cursor: '#528bff',
      diffAdded: '#98c379',
      diffRemoved: '#e06c75',
      diffModified: '#e5c07b',
    },
    fonts: {
      monospace: 'Fira Code, Monaco, Menlo, "Ubuntu Mono", monospace',
      size: 14,
      lineHeight: 1.5,
    },
    metadata: {
      author: 'Atom',
      description: 'Atom\'s iconic One Dark theme',
      version: '1.0.0',
      tags: ['popular', 'atom', 'modern'],
    },
  },

  // Material Theme Ocean
  {
    id: 'material-ocean',
    name: 'Material Ocean',
    category: 'dark',
    colors: {
      background: '#0f111a',
      foreground: '#8f93a2',
      comment: '#464b5d',
      keyword: '#c792ea',
      string: '#c3e88d',
      number: '#f78c6c',
      operator: '#89ddff',
      punctuation: '#8f93a2',
      function: '#82aaff',
      variable: '#eeffff',
      type: '#ffcb6b',
      class: '#ffcb6b',
      constant: '#f78c6c',
      property: '#eeffff',
      tag: '#f07178',
      attribute: '#c792ea',
      boolean: '#f78c6c',
      regex: '#c3e88d',
      escape: '#89ddff',
      selection: '#1f2233',
      lineHighlight: '#1a1c25',
      cursor: '#ffcc00',
      diffAdded: '#c3e88d',
      diffRemoved: '#f07178',
      diffModified: '#ffcb6b',
    },
    fonts: {
      monospace: 'Operator Mono, Fira Code, Monaco, monospace',
      size: 14,
      lineHeight: 1.6,
    },
    metadata: {
      author: 'Material Theme',
      description: 'Material Design inspired theme with ocean colors',
      version: '1.0.0',
      tags: ['material', 'modern', 'ocean'],
    },
  },

  // High Contrast Dark
  {
    id: 'high-contrast-dark',
    name: 'High Contrast Dark',
    category: 'high-contrast',
    colors: {
      background: '#000000',
      foreground: '#ffffff',
      comment: '#7ca668',
      keyword: '#569cd6',
      string: '#ce9178',
      number: '#b5cea8',
      operator: '#d4d4d4',
      punctuation: '#ffffff',
      function: '#dcdcaa',
      variable: '#9cdcfe',
      type: '#4ec9b0',
      class: '#4ec9b0',
      constant: '#4fc1ff',
      property: '#9cdcfe',
      tag: '#569cd6',
      attribute: '#92c5f8',
      boolean: '#569cd6',
      regex: '#d16969',
      escape: '#d7ba7d',
      selection: '#ffffff',
      lineHighlight: '#0a0a0a',
      cursor: '#ffffff',
      diffAdded: '#00ff00',
      diffRemoved: '#ff0000',
      diffModified: '#ffff00',
    },
    fonts: {
      monospace: 'Consolas, "Courier New", monospace',
      size: 16,
      lineHeight: 1.6,
    },
    metadata: {
      author: 'Microsoft',
      description: 'High contrast theme for better accessibility',
      version: '1.0.0',
      tags: ['accessibility', 'high-contrast', 'a11y'],
    },
  },

  // High Contrast Light
  {
    id: 'high-contrast-light',
    name: 'High Contrast Light',
    category: 'high-contrast',
    colors: {
      background: '#ffffff',
      foreground: '#000000',
      comment: '#008000',
      keyword: '#0000ff',
      string: '#a31515',
      number: '#098658',
      operator: '#000000',
      punctuation: '#000000',
      function: '#795e26',
      variable: '#001080',
      type: '#267f99',
      class: '#267f99',
      constant: '#0000ff',
      property: '#001080',
      tag: '#800000',
      attribute: '#ff0000',
      boolean: '#0000ff',
      regex: '#a31515',
      escape: '#ff0000',
      selection: '#000000',
      lineHighlight: '#f5f5f5',
      cursor: '#000000',
      diffAdded: '#00ff00',
      diffRemoved: '#ff0000',
      diffModified: '#ffff00',
    },
    fonts: {
      monospace: 'Consolas, "Courier New", monospace',
      size: 16,
      lineHeight: 1.6,
    },
    metadata: {
      author: 'Microsoft',
      description: 'High contrast light theme for better accessibility',
      version: '1.0.0',
      tags: ['accessibility', 'high-contrast', 'a11y'],
    },
  },
];

export const THEME_CATEGORIES = [
  {
    id: 'popular',
    name: 'Popular',
    description: 'Most commonly used themes',
    themes: ['vscode-dark-plus', 'github-dark', 'dracula', 'one-dark-pro'],
  },
  {
    id: 'light',
    name: 'Light Themes',
    description: 'Bright themes for well-lit environments',
    themes: ['vscode-light-plus', 'github-light', 'solarized-light'],
  },
  {
    id: 'dark',
    name: 'Dark Themes',
    description: 'Dark themes for low-light environments',
    themes: ['vscode-dark-plus', 'github-dark', 'dracula', 'monokai', 'solarized-dark', 'one-dark-pro', 'material-ocean'],
  },
  {
    id: 'high-contrast',
    name: 'High Contrast',
    description: 'Themes optimized for accessibility',
    themes: ['high-contrast-dark', 'high-contrast-light'],
  },
  {
    id: 'classic',
    name: 'Classic',
    description: 'Time-tested, well-established themes',
    themes: ['monokai', 'solarized-dark', 'solarized-light'],
  },
];